#nullable enable
#pragma warning disable CS0618

using System.CommandLine;

namespace AI21.CLI.Commands;

internal static partial class LibraryManagementV1LibraryManagementCommandApiCommand
{
    private static Option<string?> NameOption { get; } = new(
        name: @"--name")
    {
        Description = @"",
    };

    private static Option<string?> Path { get; } = new(
        name: @"--path")
    {
        Description = @"",
    };

    private static Option<global::AI21.FileStatus?> Status { get; } = new(
        name: @"--status")
    {
        Description = @"An enumeration.",
    };

    private static Option<global::System.Collections.Generic.IList<string>?> Label { get; } = new(
        name: @"--label")
    {
        Description = @"",
    };

    private static Option<int?> Limit { get; } = new(
        name: @"--limit")
    {
        Description = @"",
    };

    private static Option<int?> Offset { get; } = new(
        name: @"--offset")
    {
        Description = @"",
    };

                    private static string FormatResponse(ParseResult parseResult, global::System.Collections.Generic.IList<global::AI21.FileResponse> value, global::System.Text.Json.Serialization.JsonSerializerContext context, bool truncateLongStrings)
                    {
                        string? text = null;
                        CustomizeResponseText(parseResult, value, ref text);
                        if (!string.IsNullOrWhiteSpace(text))
                        {
                            return text;
                        }

                        var hints = new Dictionary<string, CliFormatHint>(StringComparer.OrdinalIgnoreCase)
                        {
                        };
                        CustomizeResponseFormatHints(hints);
                        return CliRuntime.FormatHumanReadable(value, context, truncateLongStrings, hints);
                    }

                    static partial void CustomizeResponseText(ParseResult parseResult, global::System.Collections.Generic.IList<global::AI21.FileResponse> value, ref string? text);
                    static partial void CustomizeResponseFormatHints(Dictionary<string, CliFormatHint> hints);


    public static Command Create()
    {
        var command = new Command(@"v1-library-management", @"Get Workspace Files
Get metadata about a specific file by file ID. The file ID is generated by
AI21 when you upload the file.");
                        command.Options.Add(NameOption);
                        command.Options.Add(Path);
                        command.Options.Add(Status);
                        command.Options.Add(Label);
                        command.Options.Add(Limit);
                        command.Options.Add(Offset);


        command.SetAction(async (ParseResult parseResult, CancellationToken cancellationToken) =>
            await CliRuntime.RunAsync(async () =>
            {
                        var name = parseResult.GetValue(NameOption);
                        var path = parseResult.GetValue(Path);
                        var status = parseResult.GetValue(Status);
                        var label = parseResult.GetValue(Label);
                        var limit = parseResult.GetValue(Limit);
                        var offset = parseResult.GetValue(Offset);
                using var client = await CliRuntime.CreateClientAsync(parseResult, cancellationToken).ConfigureAwait(false);


                                var response = await client.LibraryManagement.V1LibraryManagementAsync(
                                    name: name,
                                    path: path,
                                    status: status,
                                    label: label,
                                    limit: limit,
                                    offset: offset,
                                    cancellationToken: cancellationToken).ConfigureAwait(false);


                                if (!await CliRuntime.TryWriteOutputDirectoryAsync(
                                        parseResult,
                                        response,
                                        global::AI21.SourceGenerationContext.Default,
                                        @"$self",
                                        cancellationToken).ConfigureAwait(false))
                                {
                                await CliRuntime.WriteResponseAsync(
                                    parseResult,
                                    response,
                                    global::AI21.SourceGenerationContext.Default,
                                    FormatResponse,
                                    cancellationToken).ConfigureAwait(false);
                                }
            }, cancellationToken).ConfigureAwait(false));
        return command;
    }
}